### ISSUE TITLE
Revamp our data format (source and DB)

### ISSUE THREAD

**Issue by bochecha** [Cangjians/libcangjie#91]
@yookoala and I have been talking about this for some time now: we're not very happy with our data format:
- the source format is hard to read for humans (and the sources are primarily **for** humans)
- the db is a bit clunky (need to join two tables, frequency of a **character** in the `codes` table,...)
- etc...

I've been trying to work with [gom](http://www.hadess.net/2014/04/what-is-gom.html), a GObject ORM, and our data format definitely makes it harder than it should be. (not impossible, of course, just annoying)

So let's fix this!

**Comment by bochecha** [comment]
We've just talked with @yookoala tonight, and we're thinking about going in a radically different direction:

```yaml
- character: '：'
  simplified: null
  zh: false
  big5: false
  hkscs: false
  zhuyin: false
  kanji: false
  hiragana: false
  katakana: false
  punctuation: true
  symbol: false
  cangjie3:
  - code: rikf
    frequency: 10580
  cangjie5:
  - code: rikf
    frequency: 10580
  - code: rbhf
    frequency: 0
  shortcode:
    code: ' '
    frequency: 0
```

This is much more understandable by humans than our current format, and it's also easier to parse (it's just YAML).

I have a few reservations though, that I'd want to see addressed:

* YAML is notoriously bad at handling types, often trying to guess what you meant and picking the wrong option, then your app crashes; it might not be a problem in practice with a statically typed language like C though?
* YAML uses mapping which (depending on the language/library) might or might not preserve the order of the elements; this would make it hard to parse, modify, then reserialize as it would cause many unnecessary modifications to the data
* parsing YAML in C with libYAML seems to be too complex to be worth the trouble (we only need it in the dbbuilder) ; there's a libcyaml project which makes it much nicer, but then they don't guarantee any API/ABI stability, which could cause probles (e.g someone on a newer OS can't build) ; it's also not available in either Debian, Fedora, or Ubuntu :slightly_frowning_face:
